katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', add_todolist, name='add_todolist'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('task-changes/<int:id>', task_changes, name='task_changes'),
    path('json/', get_json, name="get_json"),
    path('add/', add_todolist_ajax, name="add_todolist_ajax" )
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class ToDoList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class ToDoListForms(forms.Form):
    title = forms.CharField(max_length=255)
    description = forms.CharField(widget=forms.TextInput)

todolist/views.py
import datetime
from multiprocessing import context
from django.shortcuts import render, redirect
from todolist.models import ToDoList
from todolist.forms import ToDoListForms
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers

# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    if request.user.is_authenticated:
        todolist = ToDoList.objects.filter(user=request.user)
        context = {
            'list_kerjaan' : todolist,
            'user_name' : request.user.username,
            'last_login': request.COOKIES['last_login'],
        }
        return render(request, 'todolist.html', context)
    
    else:
        return redirect('todolist:login')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form': form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def add_todolist(request):
    if request.user.is_authenticated:
        form = ToDoListForms(request.POST)
        if request.method == 'POST' and form.is_valid():
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            task_baru = ToDoList.objects.create(title=title, description=description,
                                                user=request.user, date=datetime.date.today())
            return redirect('todolist:show_todolist')
        
        context = {
            'form' : form,
        }
        return render(request, 'newtodolist.html', context)
    else:
        return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def add_todolist_ajax(request):
    # Pastikan user sudah log in
    if request.user.is_authenticated:
        # Ambil form-nya dari http request
        form = ToDoListForms(request.POST)
        response_data = {}
        
        # Handle jika form valid dan method request adl. POST
        if request.method == 'POST' and form.is_valid():
            # Ambil title & description dari form, buat task baru, lalu redirect
            # ke halaman utama
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            task_baru = ToDoList.objects.create(title=title, description=description,
                                                user=request.user, date=datetime.date.today())
            response_data['title'] = title
            response_data['description'] = description
            response_data['date'] = datetime.date.today()
            return JsonResponse(response_data);

        # Render halaman add task
        context = {
            'form': form,
        }
        return render(request, 'addToDoList.html', context)
    else:
        return redirect('todolist:login')

@login_required(login_url='/todolist/login/')
def task_changes(request, id):
    task_todolist = ToDoList.objects.get(id=id)
    task_todolist.is_finished = not task_todolist.is_finished
    task_todolist.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')  
def delete_task(request, id):
    task_todolist = ToDoList.objects.get(id=id)
    task_todolist.delete()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def get_json(request):
    todolist = ToDoList.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", todolist), content_type="application/json")

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<style>
  * {
    font-family: Marker Felt;
    color: rgb(0, 0, 0);
    text-align: center;
    vertical-align: middle;
  }

  body {
    background-image: url('https://images1.pixlis.com/background-image-checkers-chequered-checkered-squares-seamless-tileable-pink-flare-dark-sea-green-2368gx.png');
  }

  td,
  input {
    text-align: left;
  }

  h1 {
    font-size: 40px;
  }

  form {
    margin: auto;
    width: 400px;
    padding: 2em;
    border: 5px solid rgb(0, 0, 0);
    border-radius: 1em;
    table-layout: fixed;
    font-size: 20px;
    background-color: rgb(255, 255, 255);
  }

  h2 {
    font-size: 15px;
  }

  a,
  a.visited {
    color: rgb(244, 24, 24);
  }
</style>

<body>
  <div class="login">

    <h1>Login To Do List 🧩</h1>

    <form method="POST" action="">
      {% csrf_token %}
      <div class="username">
        <div class="col-xl-2 align-self-center">
            <label class="form-lable" for="user_username">Username:</label>
        </div>
        <div class="col align-self-center">
            <input type="text" name="username" placeholder="Input username" id="user_username" class="form-control">
        </div>
    </div>
    <div class="password">
        <div class="col-xl-2 align-self-center">
            <label class="form-lable" for="user_password">Password:</label>
        </div>
        <div class="col align-self-center">
            <input type="password" name="password" placeholder="Input password" id="user_password" class="form-control">
        </div>
    </div>
    <input type="submit" name="submit" value="Login" class="btn btn-outline-dark mx-auto d-block">
    </form>

    {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <h2>Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a></h2>

  </div>
</body>

{% endblock content %}

todolist/templates/newtodolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Add New Task</title>
{% endblock meta %}

{% block content %}

<style>
    * {
        font-family: Marker Felt;
        color: rgb(0, 0, 0);
        text-align: left;
        vertical-align: text-top;
    }

    body {
        background-image: url('https://images1.pixlis.com/background-image-checkers-chequered-checkered-squares-seamless-tileable-pink-flare-dark-sea-green-2368gx.png');
    }

    h1 {
        text-align: center;
        font-size: 35px;
    }

    form {
        margin: auto;
        width: 400px;
        padding: 1em;
        border: 3px solid rgb(228, 60, 194);
        background-color: rgb(105, 253, 157);
        border-radius: 1em;
        font-size: 17px;
        table-layout: fixed;
    }
</style>

<body>
    <div class="add_new">

        <h1>🌱 Add Task 🌱</h1>

        <form method="POST" >  
            {% csrf_token %}
            <div class="title">
                <div class="col-xl-2 align-self-center">
                    <label class="form-lable" for="user_title">Title:</label>
                </div>
                <div class="col align-self-center">
                    <input type="text" name="title" placeholder="Input title" id="user_title" class="form-control">
                </div>
            </div>
            <div class="description">
                <div class="col-xl-2 align-self-center">
                    <label class="form-lable" for="user_description">Description:</label>
                </div>
                <div class="col align-self-center">
                    <input type="text" name="description" placeholder="Input description" id="user_description" class="form-control">
                </div>
            </div>
            <input type="submit" name="submit" value="Create New Task" class="btn btn-outline-dark mx-auto d-block">
        </form>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}

<style>
    * {
        font-family: Marker Felt;
        color: rgb(0, 0, 0);
        text-align: left;
        vertical-align: text-top;
    }

    body {
        background-image: url('https://images1.pixlis.com/background-image-checkers-chequered-checkered-squares-seamless-tileable-pink-flare-dark-sea-green-2368gx.png');
    }

    h1 {
        text-align: center;
        font-size: 35px;
    }

    form {
        margin: auto;
        width: 600px;
        padding: 1em;
        border: 3px solid rgb(249, 71, 219);
        border-radius: 1em;
        font-size: 15px;
        table-layout: fixed;
    }
</style>

<body>
    <div class = "login">
    
        <h1>Create New Account</h1>  
    
            <form method="POST" >  
                {% csrf_token %}  
                <div class="row">
                    <div class="col-lg-3">
                        <label for="user_username">Username:</label>
                    </div>
                    <div class="col-lg">
                        <div class="row">
                            <input type="text" name="username" placeholder="Input username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="user_username">
                        </div>
                        <div class="row"><span class="helptext" style="color:black">Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</span>
                        </div>
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-lg-3">
                        <label for="user_password1">Password:</label>
                    </div>
                    <div class="col-lg">
                        <div class="row">
                            <input type="password" name="password1" placeholder="Input password" autocomplete="new-password" required="" id="user_password1">
                        </div>
                        <div class="row">
                            {{form.password1.help_text}}
                        </div>
                    </div>
                </div>
        
                <div class="row">
                    <div class="col-lg-3">
                        <label for="user_password2">Password confirmation:</label>
                    </div>
                    <div class="col-lg">
                        <div class="row">
                            <input type="password" name="password2" placeholder="Confirm password" autocomplete="new-password" required="" id="user_password2">
                        </div>
                        <div class="row left-buffer">
                            <p style="color:black">{{form.password2.help_text}}</p>
                            <ul>
                            {% for error in form.errors.password2 %}
                                <li>{{error}}</li>
                            {% endfor %}
                        </ul>
                        </div>
                    </div>
                </div>
                <input type="submit" name="submit" value="Register" class="btn btn-outline-dark mx-auto d-block">
            </form>
    
</body>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
<style>
    * {
        font-family: Marker Felt;
        font: black;
        text-align: center;
        vertical-align: middle;
        font-size: 15px;
        margin: auto;

    }

    body {
        background-image: url('https://images1.pixlis.com/background-image-checkers-chequered-checkered-squares-seamless-tileable-pink-flare-dark-sea-green-2368gx.png') !important;
    }

    h1 {
        margin-top: 20px;
        font-size: 35px;
        font-weight: bold;
    }

    h2 {
        font-size: 25px;
        font-weight: bold;
    }

    h3 {
        font-size: 20px;
        font-weight: bold;
    }

    h5 {
        margin-top: 20px;
    }

    .card {
        border-radius: 4px;
        background-color: rgb(255, 255, 255);
        box-shadow: 0 6px 10px rgba(0, 0, 0, 0.08), 0 0 6px rgba(0, 0, 0, .05);
        transition: .3s transform cubic-bezier(.155, 1.105, .295, 1.12), .3s -webkit-transform cubic-bezier(.155, 1.105, .295, 1.12);
    }

    .card:hover {
        transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0, 0, 0, .12), 0 4px 8px rgba(0, 0, 0, .06);
    }

    .btn-group {
        margin: center;
        vertical-align: middle;
        width: 400px;
    }

    a,
    a.visited {
        color: rgb(0, 0, 0);
    }
</style>

<body>
    <h1> TO DO LIST</h1>
        <h2>PBP/PBD Assignment 6</h2>
        <h3>🍊 Welcome {{user_name}} 🍊</h3>
        <button type="button" class="btn btn-primary done mb-2" data-bs-toggle="modal"
            data-bs-target="#exampleModal" style="text-align: center; font-family: Marker Felt;">Create new task</button>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel" style="font-weight: bold;">Create a new task
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body justify-content-center" style="display:block; margin:0 auto">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <input type="text" name="title" maxlength="255" placeholder="Title">
                        <br>
                        <input style="margin-top: 16px;" type="text" name="description" placeholder="Description">
                </div>
                <div class="modal-footer" style="justify-content: center;">
                    <button id="button" type="submit" class="button_select button_select_new"
                        data-bs-dismiss="modal">Submit</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row" id="taskCards"></div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            addTask();
        });

        document.getElementById("button").onclick = addTodo

        function addTodo() {
            fetch("{% url 'todolist:add_todolist_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(addTask)
            return false
        }

        function addTask() {
            let htmlString = "";
            $.ajax({
                url: "./json/",
                type: "GET",
                dataType: "json",
                success: function (data) {
                    data.forEach(task => {
                        var response = ""
                        if (task.fields.is_finished == true) {
                        response = "Finished 🎉"
                    } else {
                        response = "Not Finished 🥲"
                    } 

                        htmlString += `
              <div class="col-md-6 col-lg-3">
                <div class="card shadow p-3 mb-5 bg-white rounded border-0" style="padding-right: 10px;">
                    <div class="card-body d-flex flex-column">
                    <h4 class="card-title" style="font-weight: bold;">${task.fields.title}</h4>
                    <h5 class="card-text">
                        ${response}
                    </h5>
                    <p class="card-text" style="font-size: 16px;">${task.fields.date}</p>
                    <p class="card-text">${task.fields.description}</p>
                    <div class="mt-auto">
                        <a href="task-changes/${task.pk}", class="btn btn-primary done mb-2" >Task Status Change</a>
                        <a href="delete-task/${task.pk}", class="btn btn-primary done mb-2">Delete Task</a>
                    </div>
                    </div>
                </div>
                </div>
              </div>`
                            ;
                        $('#taskCards').html(htmlString);
                    })
                }, error: function (data) {
                    console.log("error");
                }
            })
        };
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
    <a href="{% url 'todolist:logout' %}" class="btn btn-primary done mb-2" style="text-align: center; font-family: Marker Felt;" >Logout</a>
    <h6>Sesi terakhir login: {{ last_login }}</h6>
</body>

</html>

{% endblock content %}